# Generated by Django 3.1.5 on 2021-02-10 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20210210_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='name',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='siteuser',
            old_name='login',
            new_name='username',
        ),
    ]
