# Generated by Django 3.1.5 on 2021-02-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20210210_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
